using Steer73.RockIT.Enums;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.DiversityDatas
{
    public class DiversityDataManager : DiversityDataManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DiversityDataManager(IDiversityDataRepository diversityDataRepository)
            : base(diversityDataRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}