using Steer73.RockIT.Enums;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Steer73.RockIT.DiversityDatas
{
    public class DiversityData : DiversityDataBase
    {
        //<suite-custom-code-autogenerated>
        protected DiversityData()
        {

        }

        public DiversityData(Guid id, Guid jobApplicationId, YesNo? happyToCompleteForm = null, AgeRange? ageRange = null, GenderOrSex? gender = null, string? otherGender = null, YesNoPreferNotToSay? genderIdentitySameAsBirth = null, GenderOrSex? sex = null, string? otherSex = null, SexualOrientation? sexualOrientation = null, string? otherSexualOrientation = null, Ethnicity? ethnicity = null, string? otherEthnicity = null, Religion? religionOrBelief = null, string? otherReligionOrBelief = null, YesNoPreferNotToSay? disability = null, EducationLevel? educationLevel = null, TypeOfSecondarySchool? typeOfSecondarySchool = null, string? otherTypeOfSecondarySchool = null, YesNoPreferNotToSayDontKnow? higherEducationQualifications = null)
            : base(id, jobApplicationId, happyToCompleteForm, ageRange, gender, otherGender, genderIdentitySameAsBirth, sex, otherSex, sexualOrientation, otherSexualOrientation, ethnicity, otherEthnicity, religionOrBelief, otherReligionOrBelief, disability, educationLevel, typeOfSecondarySchool, otherTypeOfSecondarySchool, higherEducationQualifications)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}