using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.JobFormResponses
{
    public class JobFormResponseManager : JobFormResponseManagerBase
    {
        //<suite-custom-code-autogenerated>
        public JobFormResponseManager(IJobFormResponseRepository jobFormResponseRepository)
            : base(jobFormResponseRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}