using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Steer73.RockIT.Permissions;
using Steer73.RockIT.DiversityFormResponses;

namespace Steer73.RockIT.DiversityFormResponses
{
    public class DiversityFormResponsesAppService : DiversityFormResponsesAppServiceBase, IDiversityFormResponsesAppService
    {
        //<suite-custom-code-autogenerated>
        public DiversityFormResponsesAppService(IDiversityFormResponseRepository diversityFormResponseRepository, DiversityFormResponseManager diversityFormResponseManager)
            : base(diversityFormResponseRepository, diversityFormResponseManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}