using System;

namespace Steer73.RockIT.Vacancies
{
    public class VacancyMediaSource : VacancyMediaSourceBase
    {
        //<suite-custom-code-autogenerated>
        protected VacancyMediaSource()
        {

        }

        public VacancyMediaSource(Guid id, Guid vacancyId, Guid mediaSourceId)
            : base(id, vacancyId, mediaSourceId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}
