using System;

namespace Steer73.RockIT.Vacancies
{
    public class VacancyRoleType : VacancyRoleTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected VacancyRoleType()
        {

        }

        public VacancyRoleType(Guid id, Guid vacancyId, Guid roleTypeId)
            : base(id, vacancyId, roleTypeId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}
