using Steer73.RockIT.Enums;
using Steer73.RockIT.PracticeGroups;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Identity;

namespace Steer73.RockIT.Vacancies
{
    public class Vacancy : VacancyBase
    {
        //<suite-custom-code-autogenerated>
        protected Vacancy()
        {

        }

        public Vacancy(Guid id, Guid companyId, Guid identityUserId, IReadOnlyCollection<PracticeGroup> practiceGroups, Guid? vacancyFormDefinitionId, Guid? diversityFormDefinitionId, string title, string reference, IReadOnlyCollection<Region> regions, ICollection<VacancyContributor> contributors, string description, DateOnly externalPostingDate, DateOnly closingDate, DateOnly expiringDate, bool showDiversity,bool  flagHideVacancy, string? role = null, string? benefits = null, string? location = null, string? salary = null, string? formalInterviewDate = null, string? secondInterviewDate = null, Guid? brochureFileId = null, Guid? additionalFileId = null, string? linkedInUrl = null, SyncStatus syncStatus = default, DateTime? syncStatusUpdate = null, int? externalRefId = null,
            DateTime? brochureLastUpdatedAt = null, string? projectId = null)
            : base(id, companyId, identityUserId, practiceGroups, vacancyFormDefinitionId, diversityFormDefinitionId, title, reference, regions, contributors, description, externalPostingDate, closingDate, expiringDate, showDiversity, flagHideVacancy, role, benefits, location, salary, formalInterviewDate, secondInterviewDate, brochureFileId, additionalFileId, linkedInUrl,
                  brochureLastUpdatedAt)
        {
            SyncStatus = syncStatus;
            SyncStatusUpdate = syncStatusUpdate;
            ExternalRefId = externalRefId;
            ProjectId = projectId;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public SyncStatus SyncStatus { get; set; }
        public DateTime? SyncStatusUpdate { get; set; }

        public int? ExternalRefId { get; set; }
        public string? ProjectId { get; set; }

        [NotMapped]
        public string VacancyDetailUrl { get; set; }

        public virtual VacancyStatus GetStatus(DateTime today)
        {
            var todayDateOnly = DateOnly.FromDateTime(today);

            // ClosingDate > ExpiringDate > ExternalPostingDate
            // To get current status, check starts from ClosingDate which should have the highest value to ExternalPostingDate which should have the lowest one.
            if (todayDateOnly >= ClosingDate) return VacancyStatus.Closed;
            if (todayDateOnly > ExpiringDate) return VacancyStatus.Expired;
            if (todayDateOnly >= ExternalPostingDate) return VacancyStatus.Active;

            return VacancyStatus.Pending;
        }
    }
}