using Steer73.RockIT.PracticeGroups;
using System;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Identity;

namespace Steer73.RockIT.Vacancies
{
    public class VacancyManager : VacancyManagerBase
    {
        //<suite-custom-code-autogenerated>

        public VacancyManager(
            IVacancyRepository vacancyRepository, 
            IPracticeGroupRepository practiceGroupRepository,
            IRepository<IdentityUser, Guid> identityUserRepository)
            : base(vacancyRepository, practiceGroupRepository, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}