using System;

namespace Steer73.RockIT.RoleTypes
{
    public class RoleType : RoleTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected RoleType()
        {

        }

        public RoleType(Guid id, string name, string description)
            : base(id, name, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

    }
}
