using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.Companies
{
    public class CompanyManager : CompanyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CompanyManager(ICompanyRepository companyRepository)
            : base(companyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}