using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Steer73.RockIT.Companies
{
    public class Company : CompanyBase
    {
        //<suite-custom-code-autogenerated>
        protected Company()
        {

        }

        public Company(Guid id, string? name = null, string? phone = null, string? address = null, string? postcode = null, string? primaryContact = null, string? logoUrl = null, int? externalRefId = null)
            : base(id, name, phone, address, postcode, primaryContact, logoUrl)
        {
            this.ExternalRefId = externalRefId;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        public int? ExternalRefId { get; set; }
    }
}