using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Steer73.RockIT.Permissions;
using Steer73.RockIT.JobFormResponses;

namespace Steer73.RockIT.JobFormResponses
{
    public class JobFormResponsesAppService : JobFormResponsesAppServiceBase, IJobFormResponsesAppService
    {
        //<suite-custom-code-autogenerated>
        public JobFormResponsesAppService(IJobFormResponseRepository jobFormResponseRepository, JobFormResponseManager jobFormResponseManager)
            : base(jobFormResponseRepository, jobFormResponseManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}