using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Steer73.RockIT.DiversityFormResponses
{
    public class DiversityFormResponse : DiversityFormResponseBase
    {
        //<suite-custom-code-autogenerated>
        protected DiversityFormResponse()
        {

        }

        public DiversityFormResponse(Guid id, Guid jobApplicationId, string formStructureJson, string formResponseJson)
            : base(id, jobApplicationId, formStructureJson, formResponseJson)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}