using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.DiversityFormResponses
{
    public class DiversityFormResponseManager : DiversityFormResponseManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DiversityFormResponseManager(IDiversityFormResponseRepository diversityFormResponseRepository)
            : base(diversityFormResponseRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}