using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.PracticeGroups
{
    public class PracticeGroupManager : PracticeGroupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PracticeGroupManager(IPracticeGroupRepository practiceGroupRepository)
            : base(practiceGroupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}