using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Steer73.RockIT.PracticeGroups
{
    public class PracticeGroup : PracticeGroupBase
    {
        //<suite-custom-code-autogenerated>
        protected PracticeGroup()
        {

        }

        public PracticeGroup(Guid id, string name, bool isActive)
            : base(id, name, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}