using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Steer73.RockIT.Permissions;
using Steer73.RockIT.PracticeAreas;
using Steer73.RockIT.PracticeGroups;

namespace Steer73.RockIT.PracticeAreas
{
    public class PracticeAreasAppService : PracticeAreasAppServiceBase, IPracticeAreasAppService
    {
        //<suite-custom-code-autogenerated>
        public PracticeAreasAppService(IPracticeAreaRepository practiceAreaRepository, PracticeAreaManager practiceAreaManager)
            : base(practiceAreaRepository, practiceAreaManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        private readonly IPracticeGroupRepository _practiceGroupRepository;

        public PracticeAreasAppService(
            IPracticeAreaRepository practiceAreaRepository,
            IPracticeGroupRepository practiceGroupRepository,
            PracticeAreaManager practiceAreaManager)
            : base(practiceAreaRepository, practiceAreaManager)
        {

            _practiceAreaRepository = practiceAreaRepository;
            _practiceGroupRepository = practiceGroupRepository;
            _practiceAreaManager = practiceAreaManager;

        }
        public override async Task<PagedResultDto<PracticeAreaDto>> GetListAsync(GetPracticeAreasInput input)
        {
            var totalCount = await _practiceAreaRepository.GetCountAsync(input.FilterText, input.Name, input.IsActive);
            var items = await _practiceAreaRepository.GetListAsync(input.FilterText, input.Name, input.IsActive, input.Sorting, input.MaxResultCount, input.SkipCount);

            var itemViewModel = ObjectMapper.Map<List<PracticeArea>, List<PracticeAreaDto>>(items);

            foreach (var item in itemViewModel)
            {
                var group = await _practiceGroupRepository.GetAsync(item.PracticeGroupId);
                item.PracticeGroupName = group.Name;
            }

            return new PagedResultDto<PracticeAreaDto>
            {
                TotalCount = totalCount,
                Items = itemViewModel
            };
        }
    }
}