using Steer73.RockIT.Enums;
using System;

namespace Steer73.RockIT.JobApplications
{
    public class JobApplication : JobApplicationBase
    {
        //<suite-custom-code-autogenerated>
        protected JobApplication()
        {

        }

        public JobApplication(
            Guid id, 
            Guid vacancyId,
            string firstName, 
            string lastName,
            string aka,
            string emailAddress,
            JobApplicationStatus status, 
            SyncStatus syncStatus,
            SyncStatus approveEmailStatus,
            SyncStatus rejectEmailStatus, 
            string? title = null, 
            string? phoneNumber = null, 
            string? landline = null, 
            string? currentRole = null, 
            string? currentCompany = null,
            string? currentPositionType = null,
            string? cVUrl = null, 
            string? coverLetterUrl = null, 
            string? additionalDocumentUrl = null,
            string? responseUrl = null,
            DateTime? statusUpdate = null, 
            DateTime? syncStatusUpdate = null, 
            DateTime? approveEmailUpdate = null, 
            DateTime? rejectEmailUpdate = null,
			int? externalRefId = null)
            : base(id, 
                  vacancyId, 
                  firstName, 
                  lastName, 
                  aka,
                  emailAddress, 
                  title, 
                  phoneNumber, 
                  landline, 
                  currentRole,
                  currentCompany, 
                  currentPositionType, 
                  cVUrl, 
                  coverLetterUrl, 
                  additionalDocumentUrl,
                  responseUrl)
        {
            Status = status;
            SyncStatus = syncStatus;
            ApproveEmailStatus = approveEmailStatus;
            RejectEmailStatus = rejectEmailStatus;
            StatusUpdate = statusUpdate;
            SyncStatusUpdate = syncStatusUpdate;
            ApproveEmailStatus = approveEmailStatus;
            RejectEmailStatus = rejectEmailStatus;
            ExternalRefId = externalRefId;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public JobApplicationStatus Status { get; set; }
        public SyncStatus SyncStatus { get; set; }
        public SyncStatus ApproveEmailStatus { get; set; }
        public SyncStatus RejectEmailStatus { get; set; }

        public DateTime? StatusUpdate { get; set; }
        public DateTime? SyncStatusUpdate { get; set; }
        public DateTime? ApproveEmailStatusUpdate { get; set; }
        public DateTime? RejectEmailStatusUpdate { get; set; }

		public int? ExternalRefId { get; set; }
	}
}