using Steer73.RockIT.DiversityDatas;
using Steer73.RockIT.DiversityFormResponses;
using Steer73.RockIT.FormDefinitions;
using Steer73.RockIT.JobFormResponses;
using Steer73.RockIT.Vacancies;
using System.Threading.Tasks;

namespace Steer73.RockIT.JobApplications
{
    public class JobApplicationManager : JobApplicationManagerBase
    {
        private readonly IVacancyRepository _vacancyRepository;
        private readonly IFormDefinitionRepository _formDefinitionRepository;
        private readonly DiversityDataManager _diversityDataManager;
        private readonly JobFormResponseManager _jobFormResponseManager;
        private readonly DiversityFormResponseManager _diversityFormResponseManager;

        //<suite-custom-code-autogenerated>
        public JobApplicationManager(
            IJobApplicationRepository jobApplicationRepository,
            IVacancyRepository vacancyRepository,
            IFormDefinitionRepository formDefinitionRepository,
            DiversityDataManager diversityDataManager,
            JobFormResponseManager jobFormResponseManager,
            DiversityFormResponseManager diversityFormResponseManager
            )
            : base(jobApplicationRepository)
        {
            this._vacancyRepository = vacancyRepository;
            this._formDefinitionRepository = formDefinitionRepository;
            this._diversityDataManager = diversityDataManager;
            this._jobFormResponseManager = jobFormResponseManager;
            this._diversityFormResponseManager = diversityFormResponseManager;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public async Task<JobApplication> CreateNewJobApplicationCompleteAsync(NewJobApplicationComplete newJobApplication)
        {
            var newApplication = await CreateAsync(
                newJobApplication.VacancyId,
                newJobApplication.FirstName,
                newJobApplication.LastName,
                newJobApplication.Aka,
                newJobApplication.EmailAddress,
                JobApplicationConsts.DefaultStatus,
                JobApplicationConsts.DefaultSyncStatus,
                JobApplicationConsts.DefaultSyncStatus,
                JobApplicationConsts.DefaultSyncStatus,
                newJobApplication.Title,
                newJobApplication.PhoneNumber,
                newJobApplication.Landline,
                newJobApplication.CurrentRole,
                newJobApplication.CurrentCompany,
                newJobApplication.CurrentPositionType,
                newJobApplication.CVUrl,
                newJobApplication.CoverLetterUrl,
                newJobApplication.AdditionalDocumentUrl,
                newJobApplication.ResponseUrl);

            var vacancy = await _vacancyRepository.GetAsync( newJobApplication.VacancyId);

            if (vacancy.ShowDiversity)
            {
                //Store diversity data
                await _diversityDataManager.CreateAsync(
                    newApplication.Id,
                    newJobApplication.Diversity_HappyToCompleteForm,
                    newJobApplication.Diversity_AgeRange,
                    newJobApplication.Diversity_Gender,
                    newJobApplication.Diversity_OtherGender,
                    newJobApplication.Diversity_GenderIdentitySameAsBirth,
                    newJobApplication.Diversity_Sex,
                    newJobApplication.Diversity_OtherSex,
                    newJobApplication.Diversity_SexualOrientation,
                    newJobApplication.Diversity_OtherSexualOrientation,
                    newJobApplication.Diversity_Ethnicity,
                    newJobApplication.Diversity_OtherEthnicity,
                    newJobApplication.Diversity_ReligionOrBelief,
                    newJobApplication.Diversity_OtherReligionOrBelief,
                    newJobApplication.Diversity_Disability,
                    newJobApplication.Diversity_EducationLevel,
                    newJobApplication.Diversity_TypeOfSecondarySchool,
                    newJobApplication.Diversity_OtherTypeOfSecondarySchool,
                    newJobApplication.Diversity_HigherEducationQualifications);
            }

            if (vacancy.VacancyFormDefinitionId != null)
            {
                //Store job form response
                var formDefinition = await _formDefinitionRepository.GetAsync(vacancy.VacancyFormDefinitionId.Value);
                if (!string.IsNullOrEmpty(formDefinition?.FormDetails) && !string.IsNullOrEmpty(newJobApplication.JobFormResponse))
                {
                    await _jobFormResponseManager.CreateAsync(newApplication.Id, formDefinition.FormDetails, newJobApplication.JobFormResponse);
                }
            }

            if (vacancy.DiversityFormDefinitionId != null)
            {
                //Store diversity form response
                var formDefinition = await _formDefinitionRepository.GetAsync(vacancy.DiversityFormDefinitionId.Value);
                if (!string.IsNullOrEmpty(formDefinition?.FormDetails) && !string.IsNullOrEmpty(newJobApplication.DiversityFormResponse))
                {
                    await _diversityFormResponseManager.CreateAsync(newApplication.Id, formDefinition.FormDetails, newJobApplication.DiversityFormResponse);
                }
            }

            return newApplication;
        }
    }
}