using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Steer73.RockIT.Permissions;
using Steer73.RockIT.FormDefinitions;
using Steer73.RockIT.Vacancies;
using System.Threading;

namespace Steer73.RockIT.FormDefinitions
{
    public class FormDefinitionsAppService : FormDefinitionsAppServiceBase, IFormDefinitionsAppService
    {
        protected IVacancyRepository _vacancyRepository;

        //<suite-custom-code-autogenerated>
        public FormDefinitionsAppService(
            IFormDefinitionRepository formDefinitionRepository,
            FormDefinitionManager formDefinitionManager,
            IVacancyRepository vacancyRepository)
            : base(formDefinitionRepository, formDefinitionManager)
        {
            _vacancyRepository = vacancyRepository;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        public override async Task<PagedResultDto<FormDefinitionWithNavigationPropertiesDto>> GetListAsync(GetFormDefinitionsInput input)
        {
            var pagedResultDto = await base.GetListAsync(input);
            var formDefinitionDtoList = pagedResultDto.Items.Select(x => x.FormDefinition.Id).ToArray();
            var statisticsData = await GetFormDefinitionStatisticsDataAsync(DateTime.UtcNow, formDefinitionDtoList);

            if (statisticsData != null)
            {
                foreach (var formDefinitionDto in pagedResultDto.Items)
                {
                    var statisticsItem = statisticsData.FirstOrDefault(x => x.FormDefinitionId == formDefinitionDto.FormDefinition.Id);
                    if (statisticsItem != null)
                    {
                        formDefinitionDto.FormDefinition.ActiveVacanciesCount = statisticsItem.ActiveVacanciesCount;
                        formDefinitionDto.FormDefinition.ClosedVacanciesCount = statisticsItem.ClosedVacanciesCount;
                        formDefinitionDto.FormDefinition.PendingVacanciesCount = statisticsItem.PendingVacanciesCount;
                    }
                }
            }

            return pagedResultDto;
        }

        public override async Task<FormDefinitionDto> GetAsync(Guid id)
        {
            var formDefinitionDto = await base.GetAsync(id);
            var statisticsData = await GetFormDefinitionStatisticsDataAsync(DateTime.UtcNow, [id]);

            if (statisticsData != null)
            {
                var statisticsItem = statisticsData.FirstOrDefault(x => x.FormDefinitionId == id);
                if (statisticsItem != null)
                {
                    formDefinitionDto.ActiveVacanciesCount = statisticsItem.ActiveVacanciesCount;
                    formDefinitionDto.ClosedVacanciesCount = statisticsItem.ClosedVacanciesCount;
                    formDefinitionDto.PendingVacanciesCount = statisticsItem.PendingVacanciesCount;
                }
            }

            return formDefinitionDto;
        }

        [AllowAnonymous]
        public override async Task DeleteAsync(Guid id)
        {
            var statisticsData = await GetFormDefinitionStatisticsDataAsync(DateTime.UtcNow, [id]);
            if (statisticsData != null)
            {
                var statisticsItem = statisticsData.FirstOrDefault(x => x.FormDefinitionId == id);
                if (statisticsItem != null && (statisticsItem.ActiveVacanciesCount > 0 || statisticsItem.ClosedVacanciesCount > 0))
                {
                    return;
                }
            }

            await base.DeleteAsync(id);
        }

        [AllowAnonymous]
        public override async Task<FormDefinitionDto> UpdateAsync(Guid id, FormDefinitionUpdateDto input)
        {
            // TODO: temporary added until front end controls hided.
            var statisticsData = await GetFormDefinitionStatisticsDataAsync(DateTime.UtcNow, [id]);
            if (statisticsData != null)
            {
                var statisticsItem = statisticsData.FirstOrDefault(x => x.FormDefinitionId == id);
                if (statisticsItem != null && (statisticsItem.ActiveVacanciesCount > 0 || statisticsItem.ClosedVacanciesCount > 0))
                {
                    var formDefinitionDto = await base.GetAsync(id);

                    formDefinitionDto.ActiveVacanciesCount = statisticsItem.ActiveVacanciesCount;
                    formDefinitionDto.ClosedVacanciesCount = statisticsItem.ClosedVacanciesCount;
                    formDefinitionDto.PendingVacanciesCount = statisticsItem.PendingVacanciesCount;

                    return formDefinitionDto;
                }
            }

            return await base.UpdateAsync(id, input);
        }

        public virtual async Task<List<FormDefinitionStatisticsDataItem>> GetFormDefinitionStatisticsDataAsync(DateTime checkDate, Guid[] listOfFormDefinitions = null, CancellationToken cancellationToken = default)
        {
            var results = new List<FormDefinitionStatisticsDataItem>();
            var vacancies = await _vacancyRepository.GetListOfVcanciesByFormDefinition(listOfFormDefinitions);

            var formDefinitionGroupedResults = vacancies.Where(x => x.VacancyFormDefinitionId.HasValue
                || (x.VacancyFormDefinitionId.HasValue
                    && x.DiversityFormDefinitionId.HasValue
                    && x.VacancyFormDefinitionId == x.DiversityFormDefinitionId))
                .GroupBy(x => x.VacancyFormDefinitionId);
            var diversityFormGroupedResults = vacancies.Where(x => x.DiversityFormDefinitionId.HasValue
                || (x.DiversityFormDefinitionId.HasValue
                    && x.VacancyFormDefinitionId.HasValue
                    && x.VacancyFormDefinitionId == x.DiversityFormDefinitionId))
                .GroupBy(x => x.DiversityFormDefinitionId);

            var allKeys = formDefinitionGroupedResults.Select(x => x.Key).Union(diversityFormGroupedResults.Select(x => x.Key));
            foreach (var key in allKeys)
            {
                var formDefinitionGroup = formDefinitionGroupedResults.FirstOrDefault(x => x.Key == key)?.ToArray() ?? Array.Empty<Vacancy>();
                var deversityFormDefinition = diversityFormGroupedResults.FirstOrDefault(x => x.Key == key)?.ToArray() ?? Array.Empty<Vacancy>();
                var fullDataSet = formDefinitionGroup.Union(deversityFormDefinition);

                results.Add(new FormDefinitionStatisticsDataItem
                {
                    FormDefinitionId = key.Value,
                    VacanciesTotal = fullDataSet.Count(),
                    ActiveVacanciesCount = fullDataSet.Count(x => x.GetStatus(checkDate) == Enums.VacancyStatus.Active),
                    ClosedVacanciesCount = fullDataSet.Count(x => x.GetStatus(checkDate) == Enums.VacancyStatus.Closed),
                    PendingVacanciesCount = fullDataSet.Count(x => x.GetStatus(checkDate) == Enums.VacancyStatus.Pending),
                });
            }

            return results;
        }
    }
}