using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Steer73.RockIT.Permissions;
using Steer73.RockIT.PracticeGroups;

namespace Steer73.RockIT.PracticeGroups
{
    public class PracticeGroupsAppService : PracticeGroupsAppServiceBase, IPracticeGroupsAppService
    {
        //<suite-custom-code-autogenerated>
        public PracticeGroupsAppService(IPracticeGroupRepository practiceGroupRepository, PracticeGroupManager practiceGroupManager)
            : base(practiceGroupRepository, practiceGroupManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}