using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Steer73.RockIT.PracticeAreas
{
    public class PracticeArea : PracticeAreaBase
    {
        //<suite-custom-code-autogenerated>
        protected PracticeArea()
        {

        }

        public PracticeArea(Guid id, Guid practiceGroupId, string name, bool isActive)
            : base(id, practiceGroupId, name, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}