using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.PracticeAreas
{
    public class PracticeAreaManager : PracticeAreaManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PracticeAreaManager(IPracticeAreaRepository practiceAreaRepository)
            : base(practiceAreaRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}