using System;

namespace Steer73.RockIT.MediaSources
{
    public class MediaSource : MediaSourceBase
    {
        //<suite-custom-code-autogenerated>
        protected MediaSource()
        {

        }

        public MediaSource(Guid id, string name, string description)
            : base(id, name, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

    }
}