using Steer73.RockIT.FormDefinitions;
using Steer73.RockIT.FormDefinitions;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Steer73.RockIT.FormDefinitions
{
    public class FormDefinitionManager : FormDefinitionManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FormDefinitionManager(IFormDefinitionRepository formDefinitionRepository)
            : base(formDefinitionRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}