using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Steer73.RockIT.Permissions;
using Steer73.RockIT.Companies;
// using MiniExcelLibs; // removed for OSS build
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Steer73.RockIT.Shared;
using Steer73.RockIT.Companies.External;
using Volo.Abp.BackgroundJobs;

namespace Steer73.RockIT.Companies
{
    public class CompaniesAppService : CompaniesAppServiceBase, ICompaniesAppService
    {
        protected IBackgroundJobManager _backgroundJobManager;

        //<suite-custom-code-autogenerated>
        public CompaniesAppService(
            ICompanyRepository companyRepository,
            CompanyManager companyManager,
            IDistributedCache<CompanyDownloadTokenCacheItem, string> downloadTokenCache,
            IBackgroundJobManager backgroundJobManager)
            : base(companyRepository, companyManager, downloadTokenCache)
        {
            _backgroundJobManager = backgroundJobManager;
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...

        [AllowAnonymous]
        public virtual async Task TriggerSyncAsync()
        {
            await _backgroundJobManager.EnqueueAsync(new CompanyTriggerSyncArgs());
        }
    }
}